Add missing dependencies for the gene ontology query notebooks
IDR/jupyter-docker pull request #11
Opened 2017-09-06 13:33 UTC by bramalingam

Adding a couple of python libraries to the docker file for the Gene Ontology notebooks.
Not sure if the best way is to update them here or have a requirements file in idr-py repository to manage the dependencies. Can close this PR if that sounds like a stable option.

@joshmoore @manics

2017-09-06 13:37 UTC, joshmoore commented
Don't see any particular issues here; waiting on travis.

2017-09-11 13:06 UTC, manics requested changes

2017-09-11 13:06 UTC, manics commented on Dockerfile
> +    /opt/conda/envs/python2/bin/pip install py2cytoscape pydot graphviz tqdm gseapy
Minor point on code-style: when you have multiple packages can you put them on separate lines (as in the rest of this file) to make future diffs clearer?

2017-09-19 12:08 UTC, joshmoore commented
:+1: for the update strategy. @manics: you'd target this for prod44 (as `0.4.0`)?

2017-09-19 12:48 UTC, manics commented
yes.

2017-09-19 13:56 UTC, merged

2017-09-19 13:59 UTC, joshmoore commented
0.4.0 tag of `origin/develop` pushed.